systemd: include <fcntl.h> instead of <sys/fctnl.h>
On alpine/musl we get a compiler warning:

    CC       shared/systemd/src/basic/libnm_systemd_shared_la-env-file.lo
  In file included from ../shared/systemd/src/basic/fileio.h:9,
                   from ../shared/systemd/src/basic/env-file.c:10:
  /usr/include/sys/fcntl.h:1:2: error: #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-Werror=cpp]
      1 | #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h>
        |  ^~~~~~~